const FORMAT_TIME = 'HH:mm'
const FORMAT_FULL_DATE = 'YYYY-MM-DD HH:mm:ss'
const FORMAT_DAY = 'dddd, DD MMMM'

export default {
    FORMAT_FULL_DATE: FORMAT_FULL_DATE,
    FORMAT_TIME: FORMAT_TIME,
    FORMAT_DAY: FORMAT_DAY,
}